### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by marianopela** [3ig/IdeaPad-S540-15IML-hackintosh#1]
Hey, we have the same laptop but I cannot get the touchpad to work
Now that VoodooI2C v2.3 was released (comet lake support), can you please try again to get it to work?

**Comment by 3ig** [comment]
VoodooI2C still has issues with CometLake controllers. It's still not working but is getting there. I'll commit some changes to the current config in an hour. I fixed the framebuffer lag and the battery drain.

**Comment by marianopela** [comment]
> VoodooI2C still has issues with CometLake controllers. It's still not working but is getting there. I'll commit some changes to the current config in an hour. I fixed the framebuffer lag and the battery drain.

I know, I’m trying to get help from the developers to figure it out. Appreciate the battery drain fix. That’s been bothering me since the start

**Comment by daviddean-x** [comment]
Sounds good, today I'll get my s540, so I can also provide some help. Did someone stay in contact with alexandred from Voodoo i2c?

**Comment by 3ig** [comment]
marianopela had posted his debug zip in gitter with the "Unknown synopsis type 0xffffffff error" so we are waiting for them to debug the issue. Meanwhile in trying to fix and optimize a lot of stuff in parallel i ended up messing my config last night. So i will start fresh tonight, also with a fresh installation. The current one i'm running started with Mavericks on my old Acer V5 in 2013 and was updated with every os release until now i just copied the partition to the new ssd ... to be fair i was surprised it even booted on the S540 but its since done some really strange things (like AppleALC and VoodoI2C not outputing in the kernel log for some reason).

**Comment by marianopela** [comment]
> Sounds good, today I'll get my s540, so I can also provide some help. Did someone stay in contact with alexandred from Voodoo i2c?

That's nice. The more the merrier

**Comment by marianopela** [comment]
> marianopela had posted his debug zip in gitter with the "Unknown synopsis type 0xffffffff error" so we are waiting for them to debug the issue. Meanwhile in trying to fix and optimize a lot of stuff in parallel i ended up messing my config last night. So i will start fresh tonight, also with a fresh installation. The current one i'm running started with Mavericks on my old Acer V5 in 2013 and was updated with every os release until now i just copied the partition to the new ssd ... to be fair i was surprised it even booted on the S540 but its since done some really strange things (like AppleALC and VoodoI2C not outputing in the kernel log for some reason).

Sorry to hear that. I think I'm gonna create a repo with my efi, so maybe you and @thefiredragon can help me debug it, and we can try to merge our settings

**Comment by daviddean-x** [comment]
The problem we have is our device is root pinned:

https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning

So we need to well-pinned 

`      Device (TPD0)
        {
            Name (HID2, Zero)
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x0020, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C0",
                    0x00, ResourceConsumer, _Y3B, Exclusive,
                    )
            })
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,
                    )
                    {   // Pin list
                        0x0000
                    }
            })
            Name (SBFI, ResourceTemplate ()
            {
                Interrupt (ResourceConsumer, Level, ActiveLow, ExclusiveAndWake, ,, _Y3C)
                {
                    0x00000000,
                }
            })`

**Comment by daviddean-x** [comment]
I don't have Windows installed on my machine perhaps someone could take a picture were the trackpad is located under system settings. like this: 

https://pasteboard.co/IM7q7NU.png

We have multiple TPD0 entries and we need to know which one we need to adjust.
First we need a well-pinned device than we can look for debugging. you know? root pinned devices can't be detected. so no logs. I think

**Comment by 3ig** [comment]
At least on my machine is I2C0.TPD0 and yes it is root pinned. I couldn't find any documentation about Comet Lake IRQs and therefore just guessed some GPIO pin numbers with no luck. 

[https://pasteboard.co/IM7q7NU.png](url)

I'll have more spare time to look into those stuff now around the christmas holidays so hopefuly we will make it work.

**Comment by daviddean-x** [comment]
This we'll get it to work,

https://drive.google.com/file/d/1AjVMOgybFff3WQ5OAmlZQV8Gcra5kFqN/view?usp=sharing
Here's my EFI folder, 

I owned a dell dw1820a 
There was a problem with bluetooth, also some patches where wrong at your side which I removed and added XHCI rename.  You can compare it.
So the dw1820a is working.

I know holidays are coming, I try also to take a look or we need to ask at gitter. After tested some pins did you removed the interrupt entries? 

so like how I did it in the past:
https://www.insanelymac.com/forum/topic/334815-documentation-lenovo-yoga-730-macos-1014/


I really forgot how to compare irqs how its described at the documentation.

**Comment by marianopela** [comment]
@thefiredragon mine is under PCI0.I2C0.TPAD

**Comment by marianopela** [comment]
> I don't have Windows installed on my machine perhaps someone could take a picture were the trackpad is located under system settings. like this:
> 
> https://pasteboard.co/IM7q7NU.png
> 
> We have multiple TPD0 entries and we need to know which one we need to adjust.
> First we need a well-pinned device than we can look for debugging. you know? root pinned devices can't be detected. so no logs. I think

MIne is under PCIO.I2C0.TPAD

> This we'll get it to work,
> 
> https://drive.google.com/file/d/1AjVMOgybFff3WQ5OAmlZQV8Gcra5kFqN/view?usp=sharing
> Here's my EFI folder,
> 
> I owned a dell dw1820a
> There was a problem with bluetooth, also some patches where wrong at your side which I removed and added XHCI rename. You can compare it.
> So the dw1820a is working.
> 
> I know holidays are coming, I try also to take a look or we need to ask at gitter. After tested some pins did you removed the interrupt entries?
> 
> so like how I did it in the past:
> https://www.insanelymac.com/forum/topic/334815-documentation-lenovo-yoga-730-macos-1014/
> 
> I really forgot how to compare irqs how its described at the documentation.

I tried your EFI as-is but it caused bootloop and acpi errors. I'm gonna try to readapt it to my hardware
Can you tell me the exact model of your laptop?

**Comment by marianopela** [comment]
@thefiredragon Ok so, the bootloop was caused by VoodooHDA (always a problem for me). As soon as I removed it I could boot but experienced lag at login (as I always do with the graphics configuration you and @3ig use, but that's no big deal 'cause I know how to fix it). You were right thou, bluetooth is working! Thanks. I'm gonna test it a bit and see how it performs

**Comment by daviddean-x** [comment]
You can't just use my EFI, each laptop has different hardware, on mine I don't have a o2 card reader mine is Realtek one, so I disabled it.

Also I removed from 3ig some acpi patches we don't need, also there's one OXSI.DSL which is wrong only aml will work. it's not compiled. But when you use clover rename patches you should look at your main DSDT if you have devices which are Named. So Lenovo never used MEI Device so this patch is not needed and has no effect, at the other hand Lenovo use XHCI , apple understand only XHC so we need a rename patch.

**Comment by daviddean-x** [comment]
@3ig 
Our correct pin should be 0x1C or 0x001C

**Comment by daviddean-x** [comment]
@3ig  so you have Skype ? When you like can you also write me there,  @marianopela  has an other device and it's well pinned hope it's not related to the synopsis error. 

d.faller@live.de

**Comment by 3ig** [comment]
I left the dsl files there so i can make quick changes and compile them. And looking at both your origin DSDTs there are a lot of hardware differences between our machines ( wtf Lenovo ). The login lag disappeares for me when i use MacBookPro15,1 smbios but then HDMI stops working. As for the trackpad i tried both 0x1C or 0x001C still no trackpad. I still can't get any kernel log output from voodooi2c but kextstat shows its loaded. Also the HID kext is sometimes not loading between restarts. This is getting very bizarre and confusing. 

https://drive.google.com/open?id=1tBGs9sUnZzrz5RNhOoR30GuAggIZVGtV

I stopped using skype years ago :)

**Comment by fpx-one** [comment]
[i2c  kext.zip](https://github.com/3ig/IdeaPad-S540-15IML-hackintosh/files/3991445/i2c.kext.zip)
This can be loaded, you try it, I modified the info of chid

**Comment by fpx-one** [comment]
@3ig @marianopela

**Comment by marianopela** [comment]
> [i2c kext.zip](https://github.com/3ig/IdeaPad-S540-15IML-hackintosh/files/3991445/i2c.kext.zip)
> This can be loaded, you try it, I modified the info of chid

Thanks, gonna try it asap

**Comment by daviddean-x** [comment]
For trackpad we need first solve the problem of synopsis error , voodooi2c can't patch controller and can't pickup the tpd0 device. (Ioreg)

The lagging at login is provided by CPU it's not neasesary and we can't fix that. After login there's no lagging. Speedsteps are different I think , Hopefully we have luck in future with trackpad

**Comment by fpx-one** [comment]
https://gitter.im/alexandred/VoodooI2C @3ig

**Comment by daviddean-x** [comment]
@fpx-one which device do you have? So I would play around your kext, but we also need to make our machine well-pinned. :)

**Comment by fpx-one** [comment]
https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh

**Comment by daviddean-x** [comment]
@fpx-one so I can see you got your trackpad working or not? 

looks we have same tpd0 table, when It's working could you provide your actual clover?
You provided an com.alexandred.VoodooI2CHID but at your repo above you are using voodooi2celan.kext. 

this would be really helpful, best Regards Dan

[DSDT.dsl.zip](https://github.com/3ig/IdeaPad-S540-15IML-hackintosh/files/4000293/DSDT.dsl.zip)

**Comment by neblogas** [comment]
mine is \_SB.PCI0.I2C0.TPAD

**Comment by 3ig** [comment]
Fixed. Thanks to all people involved to fix this.

**Comment by Aamirswati2** [comment]
> Fixed. Thanks to all people involved to fix this.

Hi!
Can you please tell me how you fixed this issue on comet lake?
