### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by daviddean-x** [3ig/IdeaPad-S540-15IML-hackintosh#4]
Im wondering of your issues...

> Sleep / Wake (use to work ... kind of... now it can't wake up)
Is for me working without issues

> Touchpad (VoodooI2C still can't play nice with CometLake I2C Controllers )
This is right for now hope for support comet lake

> Fingerprint reader (recognised but can't be used)
Will never work I think

> Bluetooth / Wifi (currently using an USB WiFi)
replaced by dw1820a

>Micron 2200 NVMe SSD (this is not even working on real Apple hardware)
replaced by Samsung eve plus 970

I can provide my clover if you want.

So I can't understand your sleep wake issue here...

**Comment by 3ig** [comment]
Yep ... give me your clover folder if you can. This will be helpful. Also check if you are on the latest BIOS version because there are multiple big changes ... like the card reader has differend PCI address

**Comment by daviddean-x** [comment]
I'm at the last bios version, but I have a realtek one which do not work. 

the only thing which do not work is the trackpad. Card Reader is not important for me.

**Comment by daviddean-x** [comment]
[EFI.zip](https://github.com/3ig/IdeaPad-S540-15IML-hackintosh/files/4039893/EFI.zip)

**Comment by cristianpardoo** [comment]
Hi i have a nearly identical Lenovo in terms of specs. What exactly is blocking the trackpad from running? Is it the Intel SIO Driver? I've noticed the trackpad takes work to even get working on the Windows side.

**Comment by daviddean-x** [comment]
> Hi i have a nearly identical Lenovo in terms of specs. What exactly is blocking the trackpad from running? Is it the Intel SIO Driver? I've noticed the trackpad takes work to even get working on the Windows side.

It's not a windows driver issue. It's an I2C Device and the own written driver do not work for comet lake area chipsets at the moment. Alexandred was a long time not there. So we can only hope perhaps it will never work. Or someone can code and debug them.

**Comment by fpx-one** [comment]
@3ig Please provide BIOS, run cncn11ww.exe, and extract FD from BIOS in the root directory of C disk

**Comment by cristianpardoo** [comment]
https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh/tree/master/ALCPlugFix
Installing the kexts and these commands got the trackpad working. If brightness control  is still an issue I can find that kext as well

**Comment by daviddean-x** [comment]
How did you got the trackpad under macOS working? 
Which laptop do you use ? Also an I2C device? Which changes did you do for the trackpad?
Best regards

**Comment by daviddean-x** [comment]
@cristianpardoo

**Comment by marianopela** [comment]
> How did you got the trackpad under macOS working?
> Which laptop do you use ? Also an I2C device? Which changes did you do for the trackpad?
> Best regards

<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/42821024/74587642-cb067000-4ff5-11ea-915b-3a676ff62f39.png">
He has an 8th gen CPU. No wonder it works
