### ISSUE TITLE
Micron NVME Support

### ISSUE THREAD

**Issue by ghost** [3ig/IdeaPad-S540-15IML-hackintosh#5]
Hi, I try search the Kext for micron 2200 512GB but I don’t find anything because it cause kernel panic. Please Help me

**Comment by 3ig** [comment]
There is no kext for Micron 2200. The drive just doesn't work on OSX even on real apple hardware. The only way to stop the kernel panics is to replace the drive with a compatible one or use "SSDT_NVMe-Pcc.aml" patch to stop IONVMeFamily.kext from loading and use a separate SATA drive.  
Using my SSDT_NVMe-Pcc.aml from the repo may not work for you as your NVMe SSD ACPI path may be different but give it a try. If it doesn't work here is a guide on how to build your own patch:

https://www.tonymacx86.com/threads/guide-hackrnvmefamily-co-existence-with-ionvmefamily-using-class-code-spoof.210316/

**Comment by daviddean-x** [comment]
Replace them better with an Samsung evo Plus nvme

**Comment by ghost** [comment]
Thanks
