### ISSUE TITLE
Need Help on Installation

### ISSUE THREAD

**Issue by anishtr4** [3ig/IdeaPad-S540-15IML-hackintosh#6]
I am having the same laptop which you are using. Could you please help me to get installation instructions. I tried different instruction but none of them worked. Are you using this as your regular driver?
Bios: APCN34WW
Operating System
	Windows 10 Home Single Language 64-bit
CPU
	Intel Core i5 @ 1.60GHz	54 °C
	Kaby Lake-U/Y 14nm Technology
RAM
	8.00GB
Motherboard
	LENOVO LNVNB161216 (U3E1)
Graphics
	Generic PnP Monitor (1920x1080@60Hz)
	Intel UHD Graphics 620 (Lenovo)
	2047MB NVIDIA GeForce MX250 (Lenovo)	53 °C
	SLI Disabled
Storage
	953GB SAMSUNG MZVLB1T0HALR-000L2 (Unknown (SSD))
Optical Drives
	No optical disk drives detected
Audio
	Realtek High Definition Audio(SST)

sorry for creating an issue for this.

**Comment by 3ig** [comment]
Your laptop is the same model, but with vastly different hardware. This repo is for 10gen intel CPUs (i5-10510) yours is 8gen. This efi folder won't work for you. My suggestion is to find a repo for a laptop that is closer to your config (like this [here](https://github.com/corint1/Hackintosh-Lenovo-IdeaPad-530s-14ikb)) and start form there.
