### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by richibrics** [3ig/IdeaPad-S540-15IML-hackintosh#8]
Hi I have you same CPU (i5-10210u) on my Lenovo Yoga C640.
I tried several different configuration but I always get stuck on EXITBS error.
With your EFI i get a black screen after Clover selection, but the behavior of the pc seems different (if I press the power button, it doesn't shutdown immediately like with EXITBS error or with Clover menu).
Could it be a iGPU error ? 
Thanks in advance

**Comment by 3ig** [comment]
There are some very specific to the hardware of S540 ACPI patches in this repo. I suggest you leave only those:
- SSDT-OCPublic-Merge.aml
- SSDT-PNLF-CFL.aml
- SSDT-PR00.aml

Also remove USBPorts.kext and use USBInjectAll.kext.
Remove all the device properties exept the one for the iGPU (PciRoot(0x0)/Pci(0x2,0x0)) from config.plist.

This should get you to the installer.

**Comment by marianopela** [comment]
@richibrics When stuck in preboot it's a driver problem. Unfortunately, it seems like your device and other similar Lenovos (e.g 10th gen ThinkBook series) are experiencing this same problem. For reference https://github.com/acidanthera/bugtracker/issues/1027 (è un utente che sto seguendo in questi giorni, ma sembra non ci sia nulla da fare. Ho il sospetto che sia un serio problema di drivers che non supportano il vostro hardware, almeno per il momento)

**Comment by richibrics** [comment]
@3ig tried but always black screen

**Comment by richibrics** [comment]
@marianopela Do you think these Lenovo will be compatible in the future ? - Pensi che potranno mai essere compatibili ?

**Comment by albi74** [comment]
@3ig i'll try in the afternoon.
@marianopela stays online ;-)

**Comment by albi74** [comment]
@3ig  Hi,
I followed this guide https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/coffee-lake-plus.html 

> There are some very specific to the hardware of S540 ACPI patches in this repo. I suggest you leave only those:
> 
> * SSDT-OCPublic-Merge.aml
> * SSDT-PNLF-CFL.aml
> * SSDT-PR00.aml
> 
> Also remove USBPorts.kext and use USBInjectAll.kext.
> Remove all the device properties exept the one for the iGPU (PciRoot(0x0)/Pci(0x2,0x0)) from config.plist.
> 
> This should get you to the installer.



> There are some very specific to the hardware of S540 ACPI patches in this repo. I suggest you leave only those:
> 
> * SSDT-OCPublic-Merge.aml
> * SSDT-PNLF-CFL.aml
> * SSDT-PR00.aml
> 
> Also remove USBPorts.kext and use USBInjectAll.kext.
> Remove all the device properties exept the one for the iGPU (PciRoot(0x0)/Pci(0x2,0x0)) from config.plist.
> 
> This should get you to the installer.

@3ig Hi,
I followed this guide https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/coffee-lake-plus.html , and I also followed your advice suggested in the post, but the result does not change stuck at EB # LOG:Exitbs: Start
I think it's a problem related to some driver and not kext or acpi.

Please H E L P

**Comment by 3ig** [comment]
It's most definitely a driver issue. You can try migrating to OpenCore and experiment with it's boot quirks:
`
<key>RebuildAppleMemoryMap</key>
<false/>
<key>SetupVirtualMap</key>
<true/>
<key>SignalAppleOS</key>
<false/>
<key>SyncRuntimePermissions</key>
<true/>
`

Or try this https://github.com/ReddestDream/OcQuirks if you want to go with Clover.

**Comment by albi74** [comment]
I'm already on opencore. I do some testing with the quirks you suggested to me.

tnx

**Comment by albi74** [comment]
I have tried all possible 16 combinations of these four boot quirks, but the situation has not changed I get stuck at EB # LOG:Exitbs: Start.

**Comment by richibrics** [comment]
Same for me, quirks are not the problem

**Comment by richibrics** [comment]
@albi74 any news on the idea ?

**Comment by richibrics** [comment]
The following year, with the same installer but with updated open core (same configurations) it worked.
